import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatDateISO(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export function getParisDateISO(date = new Date()): string {
  return new Intl.DateTimeFormat("fr-CA", {
    timeZone: "Europe/Paris",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

/**
 * Valide une date calendaire au format AAAA-MM-JJ. Le contrôle de format seul
 * ne suffit pas : "2026-02-30" le respecte mais n'existe pas, et serait stocké
 * tel quel dans une colonne TEXT puis comparé en string.
 */
export function isValidDateISO(value: unknown): value is string {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const parsed = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
}

/**
 * Promo-code expiration is date-only and is always read in Paris time.
 * Both legacy date-only values and full ISO timestamps begin with YYYY-MM-DD.
 */
export function isPromoCodeExpired(expiresAt: string | null, parisDateISO: string): boolean {
  if (!expiresAt) return false;
  const expirationDate = /^(\d{4}-\d{2}-\d{2})/.exec(expiresAt)?.[1];
  return expirationDate ? parisDateISO > expirationDate : false;
}

/**
 * Parse a DB timestamp (format "YYYY-MM-DD HH:MM:SS" generated by `now()` in db.ts)
 * which is stored as UTC but without a "Z" suffix. Returns a Date object correctly
 * interpreted as UTC, so toLocaleDateString with timeZone: "Europe/Paris" works.
 */
export function parseDbTimestamp(ts: string | null | undefined): Date | null {
  if (!ts) return null;
  // Already has timezone info (Z or +HH:MM/-HH:MM) → trust as-is
  if (/[Z]|[+-]\d{2}:?\d{2}$/.test(ts)) return new Date(ts);
  // DB format "YYYY-MM-DD HH:MM:SS" → treat as UTC
  return new Date(ts.replace(" ", "T") + "Z");
}

/** Format a DB timestamp for display in Paris timezone */
export function formatDbTimestamp(
  ts: string | null | undefined,
  options: Intl.DateTimeFormatOptions = { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" },
): string {
  const date = parseDbTimestamp(ts);
  if (!date) return "";
  return date.toLocaleDateString("fr-FR", { timeZone: "Europe/Paris", ...options });
}

/** Retourne le lundi de la semaine ISO (year, week) à midi UTC */
export function getISOWeekStartUTCNoon(year: number, week: number): Date {
  const jan4 = new Date(Date.UTC(year, 0, 4, 12, 0, 0));
  const day = jan4.getUTCDay() || 7;
  const mondayWeek1 = new Date(jan4);
  mondayWeek1.setUTCDate(jan4.getUTCDate() - (day - 1));
  const monday = new Date(mondayWeek1);
  monday.setUTCDate(mondayWeek1.getUTCDate() + (week - 1) * 7);
  return monday;
}

/** Get current hours and minutes in Paris timezone */
export function getParisNow(now: Date = new Date()): { hours: number; minutes: number; dateISO: string } {
  const parisTime = new Intl.DateTimeFormat("en-US", {
    timeZone: "Europe/Paris",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    hourCycle: "h23",
  }).format(now);
  const [rawHours, minutes] = parisTime.split(":").map(Number);
  const hours = rawHours % 24;
  return { hours, minutes, dateISO: getParisDateISO(now) };
}

/**
 * Clé de comparaison des rappels : `YYYY-MM-DD HH:MM`, heure murale de Paris.
 *
 * Les colonnes `bookings.date` et `bookings.start_time` stockent une heure
 * murale parisienne, pas un instant absolu. Plutôt que de convertir cette heure
 * murale en instant (direction ambiguë : 02h00-02h59 n'existe pas au passage à
 * l'heure d'été et existe deux fois au retour), on convertit `maintenant + N h`
 * DANS l'autre sens — vers l'heure murale de Paris — puis on compare des
 * chaînes. L'ordre lexicographique est exact car `start_time` est toujours
 * zéro-paddé sur 2 chiffres (cf. ALL_TIME_SLOTS dans booking.ts).
 *
 * FORMAT CRITIQUE : jamais de secondes. `date || ' ' || start_time` produit
 * "2026-08-20 10:00" ; comparer avec "2026-08-20 10:00:00" casserait l'ordre
 * lexicographique. Toujours passer par ces deux helpers, jamais concaténer à la
 * main.
 */
export function formatParisReminderKey(instant: Date = new Date()): string {
  const { hours, minutes, dateISO } = getParisNow(instant);
  return `${dateISO} ${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`;
}

/** Clé d'une réservation, à partir de ses colonnes `date` et `start_time`. */
export function bookingReminderKey(date: string, startTime: string): string {
  return `${date} ${startTime}`;
}
