import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatDateISO(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export function getParisDateISO(date = new Date()): string {
  return new Intl.DateTimeFormat("fr-CA", {
    timeZone: "Europe/Paris",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

/**
 * Parse a DB timestamp (format "YYYY-MM-DD HH:MM:SS" generated by `now()` in db.ts)
 * which is stored as UTC but without a "Z" suffix. Returns a Date object correctly
 * interpreted as UTC, so toLocaleDateString with timeZone: "Europe/Paris" works.
 */
export function parseDbTimestamp(ts: string | null | undefined): Date | null {
  if (!ts) return null;
  // Already has timezone info (Z or +HH:MM/-HH:MM) → trust as-is
  if (/[Z]|[+-]\d{2}:?\d{2}$/.test(ts)) return new Date(ts);
  // DB format "YYYY-MM-DD HH:MM:SS" → treat as UTC
  return new Date(ts.replace(" ", "T") + "Z");
}

/** Format a DB timestamp for display in Paris timezone */
export function formatDbTimestamp(
  ts: string | null | undefined,
  options: Intl.DateTimeFormatOptions = { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" },
): string {
  const date = parseDbTimestamp(ts);
  if (!date) return "";
  return date.toLocaleDateString("fr-FR", { timeZone: "Europe/Paris", ...options });
}

/** Retourne le lundi de la semaine ISO (year, week) à midi UTC */
export function getISOWeekStartUTCNoon(year: number, week: number): Date {
  const jan4 = new Date(Date.UTC(year, 0, 4, 12, 0, 0));
  const day = jan4.getUTCDay() || 7;
  const mondayWeek1 = new Date(jan4);
  mondayWeek1.setUTCDate(jan4.getUTCDate() - (day - 1));
  const monday = new Date(mondayWeek1);
  monday.setUTCDate(mondayWeek1.getUTCDate() + (week - 1) * 7);
  return monday;
}

/** Get current hours and minutes in Paris timezone */
export function getParisNow(): { hours: number; minutes: number; dateISO: string } {
  const now = new Date();
  const parisTime = new Intl.DateTimeFormat("en-US", {
    timeZone: "Europe/Paris",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    hourCycle: "h23",
  }).format(now);
  const [rawHours, minutes] = parisTime.split(":").map(Number);
  const hours = rawHours % 24;
  return { hours, minutes, dateISO: getParisDateISO(now) };
}
