/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 24fdc7bbbe6635174e765534da838b0d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ENVIRONMENT: "staging" | "production";
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
