/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 163bfbba1d1c81e5be9a4e7ba3f9da60)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ENVIRONMENT: "staging" | "production";
		CLOUDFLARE_API_TOKEN: string;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
