/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --env production` (hash: 74a368a54d25e3cbbe568337b0d80dcb)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		CLOUDFLARE_API_TOKEN: string;
		RESEND_API_KEY: string;
		INSTAGRAM_ACCESS_TOKEN: string;
		VAPID_PUBLIC_KEY: string;
		VAPID_PRIVATE_KEY: string;
		VAPID_SUBJECT: string;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
